### ISSUE TITLE
YouTrack Username/Password authentication being deprecated

### ISSUE THREAD

**Issue by timgaunt** [CaptiveAire/Seq.App.YouTrack#10]
I've heard from JetBrains that they plan to deprecate API access via the username/password in favour of token authentication. It'll be in 2019 at some point apparently but might be worth getting ahead of the change now?

See: https://twitter.com/youtrack/status/1054367747348533250

**Comment by Jaben** [comment]
Will be converting the project to dotnet core and supporting Bearer tokens at that point -- ETA is early next month.

**Comment by Jaben** [comment]
Latest supports bearer token -- but it's Seq v5.1+ only.
