### ISSUE TITLE
Exception Thrown when using localhost:XXXX YouTrack Url

### ISSUE THREAD

**Issue by geovanimartinez** [CaptiveAire/Seq.App.YouTrack#8]
I have Seq and my YouTrack instance on the same VPS server. From the ouside world I access my Seq Instance using http://logs.domain.com and my YouTrack using http://support.domain.com. When I remote desktop to my Vps, I have to access the YouTrack instance using http://localhost:9090 and Seq http://localhost:5999. When setting up the YouTrack Issue Poster app I use the following settings

![image](https://user-images.githubusercontent.com/222680/45716962-1f39c600-bb5e-11e8-980a-09d9d8a888f8.png)

I then proceed to test my settings but an app error is thrown. I seems the app is truncating my provided YouTrack Url, This might be the  reason for the exception thrown.

![image](https://user-images.githubusercontent.com/222680/45717039-57d99f80-bb5e-11e8-84b0-65fdad04d923.png)

Below is the Event Information

`{"@t":"2018-09-18T21:00:48.2044628Z","@mt":"Failure Creating Issue on YouTrack {YouTrackUrl}","@m":"Failure Creating Issue on YouTrack http://localhost80","@i":"955d4ac3","@l":"Error","@x":"YouTrackSharp.Infrastructure.InvalidRequestException: Bad Request ---> EasyHttp.Infrastructure.HttpException: BadRequest Bad Request\r\n   at EasyHttp.Http.HttpClient.ProcessRequest(String filename) in C:\\BuildAgent\\work\\f8da234c6955617\\src\\EasyHttp\\Http\\HttpClient.cs:line 229\r\n   at YouTrackSharp.Infrastructure.Connection.MakePostRequest(String command, Object data, String accept, String contentType)\r\n   at YouTrackSharp.Infrastructure.Connection.Post(String command, Object data, String accept)\r\n   at YouTrackSharp.Issues.IssueManagement.CreateIssue(Issue issue)\r\n   --- End of inner exception stack trace ---\r\n   at YouTrackSharp.Issues.IssueManagement.CreateIssue(Issue issue)\r\n   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)\r\n   at Seq.App.YouTrack.YouTrackIssuePoster.On(Event`1 event) in C:\\projects\\seq-app-youtrack\\src\\YouTrackIssuePoster.cs:line 97","YouTrackUrl":"http://localhost80","AppId":"hostedapp-34","AppInstanceId":"appinstance-229"}
`

**Comment by Jaben** [comment]
Thanks for the PR. No problem merging this one!
